[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.0"
tokio = { version="1.39.3", features=["full"] }
tokio-tungstenite = "0.23.1"
futures-util = "0.3"
anyhow = "1.0.86"
serde_json = "1.0.127"
